<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/public/css/style.css')
                        ->prependStylesheet($this->basePath() . '/public/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/public/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/public/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/public/js/jquery.min.js')
            ->prependFile($this->basePath() . '/public/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" id="header">
            <div class="navbar-inner">
                <div class="container-fluid container">
                    <div class="pull-left">
                        <a class="brand" href="javascript:void(0);">
                        </a>                    
                    </div>
                    <ul class="nav pull-right top-menu">
                        <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">Dropdown <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                              <li><a href="#">Profile Setting</a></li>
                              <li><a href="#">Logout</a></li>
                            </ul>
                        </li> 
                    </ul>
                </div>    
            </div>
        </div>  
        <div class="container body_container">
            <div id="sidebar-wrapper">
                <div id="sidebar" class="" style="margin-left: 0px;">
                    <nav>
                        <ul class="nav">
                            <li><a href="#" id="btn-1" data-toggle="collapse" data-target="#submenu1" aria-expanded="false">Dashboard</a>
                                    <ul class="nav collapse" id="submenu1" role="menu" aria-labelledby="btn-1">
                                            <li><a href="#">Lin1</a></li>
                                            <li><a href="#">Link1</a></li>
                                            <li><a href="#">Link3</a></li>
                                    </ul>
                            </li>
                            <li><a href="#">Link 3</a></li>
                            <li><a href="#">Link 4</a></li>
                        </ul>
                    </nav>
                </div>
                
            </div>
            <?php echo $this->content; ?>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>        
        </div> <!-- /container -->            
        <?php echo $this->inlineScript() ?>
    </body>
</html>
